### ISSUE TITLE
.NET Api Key requirement for proxy sdk

### ISSUE THREAD

**Issue by adriaanp** [splitio/.net-core-client#194]
With the Javascript SDK we can provide an empty api key when connecting to a split proxy.
```
core: {
        // This is set by the proxy config
        authorizationKey: '',
        key: user.id?.toString() ?? '',
      },
```

Why is an Api key required for the .NET SDK if connecting to a split proxy?

**Comment by chillaq** [comment]
Hi @adriaanp , in theory you don't need the API Key in SDK if it is using Synchronizer as proxy, however, you can still use a network proxy instead of Split Synchronizer, the proxy just need to relay the URL sent by SDK. Which means the SDK has to use a valid SDK API Key, otherwise the calls will fail to authenticate.

The Synchronizer also provide a custom API Key that SDK can use to authenticate connecting SDKs to it.

Hope that helps.
